/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		403: typeof import("./src/components/ErrorMessage/403.vue")["default"];
		404: typeof import("./src/components/ErrorMessage/404.vue")["default"];
		500: typeof import("./src/components/ErrorMessage/500.vue")["default"];
		AAlert: typeof import("ant-design-vue/es")["Alert"];
		AAnchorLink: typeof import("ant-design-vue/es")["AnchorLink"];
		AAutoComplete: typeof import("ant-design-vue/es")["AutoComplete"];
		AAvatar: typeof import("ant-design-vue/es")["Avatar"];
		ABadge: typeof import("ant-design-vue/es")["Badge"];
		ABreadcrumb: typeof import("ant-design-vue/es")["Breadcrumb"];
		ABreadcrumbItem: typeof import("ant-design-vue/es")["BreadcrumbItem"];
		AButton: typeof import("ant-design-vue/es")["Button"];
		ACard: typeof import("ant-design-vue/es")["Card"];
		ACardGrid: typeof import("ant-design-vue/es")["CardGrid"];
		ACol: typeof import("ant-design-vue/es")["Col"];
		AConfigProvider: typeof import("ant-design-vue/es")["ConfigProvider"];
		ADescriptions: typeof import("ant-design-vue/es")["Descriptions"];
		ADescriptionsItem: typeof import("ant-design-vue/es")["DescriptionsItem"];
		ADivider: typeof import("ant-design-vue/es")["Divider"];
		ADrawer: typeof import("ant-design-vue/es")["Drawer"];
		ADropdown: typeof import("ant-design-vue/es")["Dropdown"];
		AInput: typeof import("ant-design-vue/es")["Input"];
		ALayout: typeof import("ant-design-vue/es")["Layout"];
		ALayoutContent: typeof import("ant-design-vue/es")["LayoutContent"];
		ALayoutFooter: typeof import("ant-design-vue/es")["LayoutFooter"];
		ALayoutHeader: typeof import("ant-design-vue/es")["LayoutHeader"];
		ALayoutSider: typeof import("ant-design-vue/es")["LayoutSider"];
		AList: typeof import("ant-design-vue/es")["List"];
		AListItem: typeof import("ant-design-vue/es")["ListItem"];
		AListItemMeta: typeof import("ant-design-vue/es")["ListItemMeta"];
		AMenu: typeof import("ant-design-vue/es")["Menu"];
		AMenuDivider: typeof import("ant-design-vue/es")["MenuDivider"];
		AMenuItem: typeof import("ant-design-vue/es")["MenuItem"];
		AModal: typeof import("ant-design-vue/es")["Modal"];
		APopover: typeof import("ant-design-vue/es")["Popover"];
		ARow: typeof import("ant-design-vue/es")["Row"];
		ASpace: typeof import("ant-design-vue/es")["Space"];
		ASubMenu: typeof import("ant-design-vue/es")["SubMenu"];
		ASwitch: typeof import("ant-design-vue/es")["Switch"];
		ATabPane: typeof import("ant-design-vue/es")["TabPane"];
		ATabs: typeof import("ant-design-vue/es")["Tabs"];
		ATooltip: typeof import("ant-design-vue/es")["Tooltip"];
		ATypographyText: typeof import("ant-design-vue/es")["TypographyText"];
		ATypographyTitle: typeof import("ant-design-vue/es")["TypographyTitle"];
		CompactHeaders: typeof import("./src/components/CompactHeaders/index.vue")["default"];
		CopyOptBtn: typeof import("./src/components/CopyOptBtn/index.vue")["default"];
		CountUp: typeof import("./src/components/CountUp/index.vue")["default"];
		Empty: typeof import("./src/components/Empty/index.vue")["default"];
		GRoleSelect: typeof import("./src/components/GSelect/GRoleSelect.vue")["default"];
		ImportExcel: typeof import("./src/components/ImportExcel/index.vue")["default"];
		Pagination: typeof import("./src/components/ProTable/components/Pagination.vue")["default"];
		ParticleClock: typeof import("./src/components/ParticleClock/index.vue")["default"];
		ProTable: typeof import("./src/components/ProTable/index.vue")["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		SearchForm: typeof import("./src/components/SearchForm/index.vue")["default"];
		SelectFilter: typeof import("./src/components/SelectFilter/index.vue")["default"];
		SvgIcon: typeof import("./src/components/SvgIcon/index.vue")["default"];
		SwitchDark: typeof import("./src/components/SwitchDark/index.vue")["default"];
		TableFilter: typeof import("./src/components/TableFilter/index.vue")["default"];
		TablePreview: typeof import("./src/components/TablePreview/index.vue")["default"];
		TableTooltip: typeof import("./src/components/TableTooltip/index.vue")["default"];
		TabRightMenu: typeof import("./src/components/ContextMenu/tabRightMenu.vue")["default"];
		ThemeColor: typeof import("./src/components/ThemeColor/index.vue")["default"];
	}
}
