/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		403: typeof import("./src/components/ErrorMessage/403.vue")["default"];
		404: typeof import("./src/components/ErrorMessage/404.vue")["default"];
		500: typeof import("./src/components/ErrorMessage/500.vue")["default"];
		AButton: typeof import("ant-design-vue/es")["Button"];
		AForm: typeof import("ant-design-vue/es")["Form"];
		AFormItem: typeof import("ant-design-vue/es")["FormItem"];
		AInput: typeof import("ant-design-vue/es")["Input"];
		AInputPassword: typeof import("ant-design-vue/es")["InputPassword"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		SvgIcon: typeof import("./src/components/SvgIcon/index.vue")["default"];
	}
}
